# Generated by Django 4.1 on 2022-09-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nationality',
            field=models.CharField(choices=[('Kenya', 'Kenya'), ('Tanzanian', 'Tanzanian'), ('Rwandees', 'Rwandees')], max_length=15, null=True),
        ),
    ]
