# Generated by Django 4.1 on 2022-09-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_customer_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='employment_status',
            field=models.BooleanField(choices=[('married', 'Married'), ('Single', 'Single'), ('Engaged', 'Engaged')], max_length=30, null=True),
        ),
    ]
