# Generated by Django 4.1 on 2022-09-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_customer_employment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='employment_status',
            field=models.BooleanField(choices=[('Selfemployed', 'Selfemployed'), ('Employed', 'Employed')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(choices=[('married', 'Married'), ('Single', 'Single'), ('Engaged', 'Engaged')], max_length=8, null=True),
        ),
    ]
