# Generated by Django 4.1 on 2022-09-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_alter_customer_employment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='issue_date',
            field=models.DateTimeField(),
        ),
    ]
