# Generated by Django 4.1 on 2022-09-07 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_alter_card_issue_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Third_Party',
            new_name='ThirdParty',
        ),
    ]
